### PR TITLE
Converting An Enum To A String Benchmark

### PR DESCRIPTION
**Pull request by Erfan-ffa**
hey mj,
I've added a benchmark for converting an enum to string using different available methods. 
You didn't  put any "Contribution" instruction but I tried to follow your patterns in code, but if you find any problem I'll be so happy if you tell me.

@mjebrahimi

### CODE REVIEW

**Comment by mjebrahimi** [comment]
Hi Erfan
Thank you, and sorry for my late response, I have been quite busy the past few days.
I haven't thought of a contribution cause I created it for my personal purpose but you did it well and I appreciate it.
Your contribution is good enough and I merged it but could you use [BenchmarkDotNetVisualizer](https://github.com/mjebrahimi/BenchmarkDotNetVisualizer/) to create awesome and colorful reports from your benchmarks?

**Comment by Erfan-ffa** [comment]
Thank you for your kind words and for merging my contribution. I’m glad you found it useful. I will definitely check [BenchmarkDotNetVisualizer](https://github.com/mjebrahimi/BenchmarkDotNetVisualizer/) out. I will work on it and create a pull request in the next couple of days.

**Comment by mjebrahimi** [comment]
BTW it's worth it to add more benchmarks for these Enum libraries as well, especially the last one which utilizes source generator.
- https://www.nuget.org/packages/Enums.NET
- https://www.nuget.org/packages/FastEnum
- https://www.nuget.org/packages/EnumStringValues
- https://www.nuget.org/packages/EnumUtils/2.1.8-pre
- https://www.nuget.org/packages/NetEscapades.EnumGenerators/1.0.0-beta08

**Comment by Erfan-ffa** [comment]
Good idea. I'm also curious to see how they compare to the other libraries in terms of performance and memory usage. I plan to update my work with more benchmarks in the next few weeks.

**Comment by mjebrahimi** [comment]
Hi Erfan, please submit your PR https://github.com/mjebrahimi/BenchmarkDotNetVisualizer/pull/2 in this repo.
I am also looking forward to your next PR about benchmarks between those mentioned libraries https://github.com/mjebrahimi/Performance-Wars-Benchmarking-CSharp/pull/1#issuecomment-1935613053

**Pull request merged**
