### PR TITLE
VisualizedBenchmark for converting enum to string benchmark

### PR DESCRIPTION
**Pull request by Erfan-ffa**
Hi Mj,
I apologize for any confusion and the delay in my response.
I will create a PR as soon as I can for benchmarks between those libraries.
however if there are any further suggestions or problems with this PR, please let me know :)

### CODE REVIEW

**Comment by mjebrahimi** [comment]
No problem, don't mention it. :)
Honestly, the way you used BenchmarkDotNetVisualizer is incorrect, but let me fix it for you. so I merge it and fix it.
For that benchmark please also consider this library ([Enum.Source.Generator](https://github.com/EngRajabi/Enum.Source.Generator)) as well.

**Comment by mjebrahimi** [comment]
Erfan, I just made some trivial updates to your code.
Please check out the result and let me know if there are any questions or anything else.

**Comment by Erfan-ffa** [comment]
Great changes, thanks.

**Comment by mjebrahimi** [comment]
You're welcome

**Pull request merged**
